---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
  description: meta description
- type: text
  name: bg_image_webp
  label: bg_image_webp
  description: page title background image webp
- type: file
  name: bg_image
  label: bg_image
  description: page title background image
- type: text
  name: image_webp
  label: image_webp
  description: service image webp
- type: file
  name: image
  label: image
  description: service image
- type: text
  name: icon
  label: icon
  description: service icon [fontawesome 4.7 icon pack]
- type: text
  name: type
  label: type
  default: service
